### PR TITLE
[DS-1606] Bring dspace-solr up-to-date with current development environment

### PR DESCRIPTION
**Pull request by mwoodiupui**

### CODE REVIEW

**Comment by helix84** [comment]
Please, throw this in, too:
https://github.com/DSpace/DSpace/commit/4436ad96bbd8aa59c25fc4ecf3ea7754da57387f

**Comment by KevinVdV** [comment]
Hi Mark,

I like this work, but it got me wondering why is the DSpace solr still a separate project ? Should we not move into the DSpace core in its entire ?

**Comment by tdonohue** [comment]
These changes all look fine to me, +1.

Regarding @KevinVdV 's note above -- we could discuss whether we just merge this over into "core" (DSpace/DSpace).  I think the only reason it hasn't been moved is that it's a very small bit of code (2 java classes) that we've rarely updated in the past.

We could talk about it a bit more in this week's meeting, to see what people think. Either way though, I think we should still merge this PR, as this codebase doesn't even build properly as is.

**Comment by mwoodiupui** [comment]
I don't see why we should not fold dspace-solr into DSpace, if there is consensus, and I'd be happy to do the work, but I think that that is a separate issue.

**Pull request merged**
